/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for sm2signature
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder sm2signature_decoder;

extern int sm2_get_signature_r(void *context, size_t hdrlen,
		unsigned char tag, const void *value, size_t vlen);
extern int sm2_get_signature_s(void *context, size_t hdrlen,
		unsigned char tag, const void *value, size_t vlen);
