# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015 - 2022 Beijing WangXun Technology Co., Ltd.
#
# Makefile for the Wangxun(R) 10GbE PCI Express ethernet driver
# virtual functions.
#

obj-$(CONFIG_TXGBEVF) += txgbevf.o

txgbevf-objs := txgbevf_main.o txgbe_vf.o \
				txgbe_mbx.o txgbe_txrx.o