# the kernel config arch list, the ANCK downstream distributions could override it
# eg: DIST_CONFIG_KERNEL_ARCHS_FOO = x86 x86-debug
DIST_CONFIG_KERNEL_ARCHS_ANCK = x86 x86-debug arm64 arm64-debug

# the kernel configs dependencies.
# For ANCK, it is empty
# The ANCK downstream distributions could override it
# eg: DIST_CONFIG_KERNEL_DEPENDENCIES_FOO = ANCK
DIST_CONFIG_KERNEL_DEPENDENCIES_ANCK =